services:
  frontend:
    container_name: react-monitor
    build: ./frontend/
    networks:
      - client-side
    ports:
      - 3000:3000
    volumes:
      - .:/code

  backend:
    container_name: go-api
    build: ./backend/
    env_file: ./.env
    networks:
      - client-side
      - server-side
    ports:
      - 4000:4000
    volumes:
      - .:/code

  db:
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_DB=monitor
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  client-side: {}
  server-side: {}

volumes:
  db-data: {}
