services:
  frontend:
    container_name: react-monitor
    build: ./frontend/
    networks:
      - client-side
    ports:
      - 3000:3000
    volumes:
      - .:/code
  backend:
    container_name: flask
    build: ./backend/
    env_file: ./.env
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    networks:
      - client-side
      - server-side
    ports:
      - 4000:4000
    volumes:
      - .:/code

networks:
  client-side: {}
  server-side: {}

volumes:
  db-data: {}
